version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    depends_on:
      - redis
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app/
    command: python manage.py runserver 0.0.0.0:8000
    # environment:
    #   - name=value
    container_name: backend
    environment:
      - SECRET_KEY=test
      - DEBUG=True

  worker:
    build: .
    depends_on:
      - redis
      - backend
    volumes:
      - ./core:/app/
    command: celery -A core worker -l INFO

  smtp4dev:
      image: rnwood/smtp4dev:v3
      restart: always
      ports:
        - '5000:80'
        - '25:25'
        - '143:143'
      volumes:
        - smtp4dev-data:/smtp4dev
      environment:
        - ServerOptions__HostName=smtp4dev
    
    
volumes:
  smtp4dev-data:
