name: Django-Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setting up docker
      run: docker-compose up -d
    - name: Flake8 and pytest testing 
      run: docker exec backend sh -c 'flake8 && pytest .'
